Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 33

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 8

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/setup'
  - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'
  - 'config/routes.rb'

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 140

AllCops:
  Exclude:
  - 'bin/**/*'
  - 'script/**/*'
  - 'log/**/*'
  - 'public/**/*'
  - 'tmp/**/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'lib/tasks/heroku_clear_tasks.rake'

inherit_from: .rubocop_todo.yml
